config/routes.rb
Rails.application.routes.draw do
  resources :user_mistakes
  resources :mistakes
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "user_mistakes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/mistake.rb
class Mistake < ApplicationRecord
    has_many :user_mistakes, :dependent => :destroy
    has_many :users, through: :user_mistakes
    validates :name, presence: true
    validates :severity, presence: true
    validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_mistakes, :dependent => :destroy
    has_many :mistakes, through: :user_mistakes
end

app/models/user_mistake.rb
class UserMistake < ApplicationRecord
    belongs_to :user
    belongs_to :mistake
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mistakes_controller.rb
class MistakesController < ApplicationController
  before_action :set_mistake, only: %i[ show edit update destroy ]

  # GET /mistakes or /mistakes.json
  def index
    @mistakes = Mistake.all
    respond_to do |format|
      format.html
      format.json { render json: MistakesDatatable.new(view_context) }
    end
  end

  # GET /mistakes/1 or /mistakes/1.json
  def show
  end

  # GET /mistakes/new
  def new
    @mistake = Mistake.new
  end

  # GET /mistakes/1/edit
  def edit
  end

  # POST /mistakes or /mistakes.json
  def create
    @mistake = Mistake.new(mistake_params)

    respond_to do |format|
      if @mistake.save
        # set the mistake_id after mistake's creation
        mistake_id = @mistake.id
        UserMistake.last.update_attribute(mistake_id: mistake_id)
        format.html { redirect_to mistake_url(@mistake), notice: "Mistake was successfully created." }
        format.json { render :show, status: :created, location: @mistake }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mistakes/1 or /mistakes/1.json
  def update
    respond_to do |format|
      if @mistake.update(mistake_params)
        format.html { redirect_to mistake_url(@mistake), notice: "Mistake was successfully updated." }
        format.json { render :show, status: :ok, location: @mistake }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mistakes/1 or /mistakes/1.json
  def destroy
    @mistake.destroy!

    respond_to do |format|
      format.html { redirect_to mistakes_url, notice: "Mistake was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mistake
      @mistake = Mistake.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mistake_params
      params.require(:mistake).permit(:name, :description, :severity)
    end
end

app/controllers/user_mistakes_controller.rb
class UserMistakesController < ApplicationController
  before_action :set_user_mistake, only: %i[ show edit update destroy ]

  # GET /user_mistakes or /user_mistakes.json
  def index
    @user_mistakes = UserMistake.all
    respond_to do |format|
      format.html
      format.json { render json: UserMistakesDatatable.new(view_context) }
    end
  end

  # GET /user_mistakes/1 or /user_mistakes/1.json
  def show
  end

  # GET /user_mistakes/new
  def new
    @user_mistake = UserMistake.new
  end

  # GET /user_mistakes/1/edit
  def edit
  end

  # POST /user_mistakes or /user_mistakes.json
  def create
    @user_mistake = UserMistake.new(user_mistake_params)

    respond_to do |format|
      if @user_mistake.save
        format.html { redirect_to user_mistakes_url, notice: "Mistake successfully logged." }
        format.json { render :show, status: :created, location: @user_mistake }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_mistakes/1 or /user_mistakes/1.json
  def update
    respond_to do |format|
      if @user_mistake.update(user_mistake_params)
        format.html { redirect_to user_mistake_url(@user_mistake), notice: "User mistake was successfully updated." }
        format.json { render :show, status: :ok, location: @user_mistake }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_mistakes/1 or /user_mistakes/1.json
  def destroy
    @user_mistake.destroy!

    respond_to do |format|
      format.html { redirect_to user_mistakes_url, notice: "User mistake was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_mistake
      @user_mistake = UserMistake.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_mistake_params
      params.require(:user_mistake).permit(:user_id, :mistake_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  # GET /users or /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context) }
    end
  end
  # GET /users/1 or /users/1.json
  def show
  end
  # GET /users/new
  def new
    @user = User.new
  end
  
  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mistakes_helper.rb
module MistakesHelper
end

app/helpers/user_mistakes_helper.rb
module UserMistakesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whoops!: Log Your Dev Mistakes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" type="image/x-icon" href="/assets/favicons.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
  </head>

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="/assets/404-error.png" alt="Logo" width="50" height="50" class="d-inline-block">
      Whoops!
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/mistakes">Mistakes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/mistakes/new">Create Mistake</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/user_mistakes/new">Log Mistake</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>

  <footer>
    <div class="fixed-bottom">
      <p id="footer-text">© 2024 Anjali Venkatesh, Solution Street</p>
    </div>
  </footer>
</html>

app/views/mistakes/_form.html.erb
  <%= form_with(model: mistake) do |form| %>
    <% if mistake.errors.any? %>
      <div style="color: red">
        <ul>
          <% mistake.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="row">
      <div class="col-sm-4">
        <%= form.label "Type of Error:", class: "form-label"%>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <%= form.label "Severity of Error:", class: "form-label" %>
        <%= form.text_field :severity, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <%= form.label "Write a small description:", class: "form-label" %>
        <%= form.text_field :description, class: "form-control" %>
      </div>
    </div>
    
    <div>
    <%= form.submit "Submit", class: "btn btn-outline-danger"%>
    <button class="btn btn-outline-danger"><%= link_to "Cancel", mistakes_path %></button>
    </div>
  <% end %>

app/views/mistakes/_mistake.html.erb
<div id="<%= dom_id mistake %>">
</div>

app/views/mistakes/edit.html.erb
<div class="container form-contain">
  <h1>Editing mistake</h1>

  <%= render "form", mistake: @mistake %>
</div>

app/views/mistakes/index.html.erb
<div id="mistakes" class="container table-contain">
<p style="color: #75B9BE"><%= notice %></p>

<h1>Mistakes</h1>

  <table class='table table-striped' id='mistakes_table' data-source='<%= mistakes_url(format: :json) %>'>
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Severity</th>
      <th>Created At</th>
      <th>Description</th>
    </thead>
    <tbody>
    </tbody>
  </table>

  <button class='btn btn-outline-danger'><%= link_to "New Mistake", new_mistake_path %></button>
</div>

app/views/mistakes/new.html.erb
<div class="container form-contain">
  <h1>New Mistake</h1>
  <%= render "form", mistake: @mistake %>
</div>

app/views/mistakes/show.html.erb
<div class="container table-contain">
  <p style="color: #75B9BE"><%= notice %></p>

  <%= render @mistake %>

  <h1><%= @mistake.name %></h1>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th scope="row">#</th>
        <td><%= @mistake.id %></td>
      </tr>
      <tr>
        <th scope="row">Severity</th>
        <td><%= @mistake.severity %></td>
      </tr>
      <tr>
        <th scope="row">About</th>
        <td><%= @mistake.description %></td>
      </tr>
    </tbody>
  </table>

  
    <button class='btn btn-outline-danger'><%= link_to "Edit", edit_mistake_path(@mistake) %></button>
    <button class='btn btn-outline-danger'> <%= link_to 'Delete', mistake_path(@mistake), 
    data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></button>

</div>

app/views/user_mistakes/_form.html.erb
<%= form_with(model: user_mistake) do |form| %>
  <% if user_mistake.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_mistake.errors.count, "error") %> prohibited this user_mistake from being saved:</h2>

      <ul>
        <% user_mistake.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-sm-4">
        <%= form.label "Select a User:", class: "form-label"%>
        <%= form.collection_select(:user_id, User.all, :id, :name, { prompt: "Who's the culprit?" },{class: "form-select"}) %>
        <%= form.label "Select a Mistake:", class: "form-label"%>
        <%= form.collection_select( :mistake_id, Mistake.all, :id, :name, { prompt: "What crimes?" },{class: "form-select"}) %>
      </div>
  </div>
  <div>
    <%= form.submit "Submit", class: "btn btn-outline-danger"%>
    <button class="btn btn-outline-danger"><%= link_to "Cancel", user_mistakes_path %></button>
  </div>
<% end %>

app/views/user_mistakes/_user_mistake.html.erb
<div id="<%= dom_id user_mistake %>">
</div>

app/views/user_mistakes/edit.html.erb
<h1>Editing user mistake</h1>

<%= render "form", user_mistake: @user_mistake %>

<br>

<div>
  <%= link_to "Show this user mistake", @user_mistake %> |
  <%= link_to "Back to user mistakes", user_mistakes_path %>
</div>

app/views/user_mistakes/index.html.erb
<div class="container table-contain">
  <p style="color: #75B9BE"><%= notice %></p>

  <h1>Master Table</h1>

<table class='table table-striped' id='user_mistakes_table' data-source='<%= user_mistakes_url(format: :json) %>'>
    <thead>
      <th>ID</th>
      <th>User</th>
      <th>Mistake</th>
      <th>Created At</th>
    </thead>
    <tbody>
    </tbody>
  </table>

  <button class='btn btn-outline-danger'><%= link_to "Log a Mistake", new_user_mistake_path %></button>
</div>

app/views/user_mistakes/new.html.erb
<div class="container form-contain">
<h1>Log a New Mistake</h1>

<%= render "form", user_mistake: @user_mistake %>
</div>

app/views/user_mistakes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_mistake %>

<div>
  <%= link_to "Edit this user mistake", edit_user_mistake_path(@user_mistake) %> |
  <%= link_to "Back to user mistakes", user_mistakes_path %>

  <%= button_to "Destroy this user mistake", @user_mistake, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
      <div class="col-sm-4">
        <%= form.label "Full name:", class: "form-label"%>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <%= form.label "Email:", class: "form-label" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
    </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-outline-danger"%>
    <button class="btn btn-outline-danger"><%= link_to "Cancel", users_path %></button>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<div class="container form-contain">
  <h1>Editing user</h1>
  <%= render "form", user: @user %>`

</div>

app/views/users/index.html.erb
<div class='container table-contain'>

  <p style="color: #75B9BE"><%= notice %></p>

  <h1>Users</h1>

  <table class='table table-striped' id='users_table' data-source='<%= users_url(format: :json) %>'>
    <thead>
      <th>ID</th>
      <th>Email</th>
      <th>Name</th>
      <th>Created At</th>
      <th>Mistakes</th>
    </thead>
    <tbody>
    </tbody>
  </table>

  <button class='btn btn-outline-danger'><%= link_to "New User", new_user_path %></button>

</div>

app/views/users/new.html.erb
<div class="container form-contain">
  <h1>New user</h1>
  <%= render "form", user: @user %>
</div>

app/views/users/show.html.erb
<div class="container table-contain">
  <p style="color: #75B9BE"><%= notice %></p>

  <%= render @user %>

  <h1><%= @user.name %></h1>
  <table class="table table-striped">
    <tbody>
      <tr>
        <th scope="row">#</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th scope="row">Email</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th scope="row">Mistakes</th>
        <td><%= @user.mistakes.count %></td>
      </tr>
    </tbody>
  </table>

  
  <button class='btn btn-outline-danger'><%= link_to "Edit", edit_user_path(@user) %></button>
  <button class='btn btn-outline-danger'> <%= link_to 'Delete', user_path(@user), 
  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></button>
</div>